# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    cd Installer
    makensis "/XOutFile $(Build.ArtifactStagingDirectory)/openHAB-setup.exe" openhab.nsi
  displayName: 'Build openHAB Windows installer'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/openHAB-setup.exe'
    ArtifactName: 'installer'
    publishLocation: 'Container'